{% set name = "fa2" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a12e0a7dc228999c605beaae751424ec4a4f60281f44683c0744a72fc9141ef

build:
  number: 1
  script:
    # Delete old generated c file so that cython can generate new ones
    # Otherwise, it will be incompatible with python 3.9+
    - rm -f fa2/fa2util.c    # [unix]
    - del /f /q fa2\fa2util.c   # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - numpy
    - python
    - scipy
    - tqdm

test:
  imports:
    - fa2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bhargavchippada/forceatlas2
  summary: 'The fastest ForceAtlas2 algorithm for Python (and NetworkX)'
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://pypi.org/project/fa2/
  dev_url: https://github.com/bhargavchippada/forceatlas2

extra:
  recipe-maintainers:
    - msadang
