{% set name = "fa2" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb38954bc867b46b08d4f7f39e5886e107b407ba1e30742aab265f6b5c3fbf17

build:
  number: 0
  script:
    # Delete old generated c file so that cython can generate new ones
    # Otherwise, it will be incompatible with python 3.9+
    - rm -f fa2/fa2util.c    # [unix]
    - del /f /q fa2\fa2util.c   # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
  run:
    - numpy
    - python
    - scipy
    - tqdm

test:
  imports:
    - fa2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bhargavchippada/forceatlas2
  summary: 'The fastest ForceAtlas2 algorithm for Python (and NetworkX)'
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://pypi.org/project/fa2/
  dev_url: https://github.com/bhargavchippada/forceatlas2

extra:
  recipe-maintainers:
    - msadang
